name: incontrol_flutter
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.4
  flutter_bloc: ^8.0.0
  flow_builder: ^0.0.6
  flutter_svg: ^1.0.0
  dartz: ^0.10.1
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.6.0  
  google_sign_in: ^5.4.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  the_apple_sign_in: ^1.1.1
  dio: ^4.0.6
  firebase_crashlytics: ^3.0.8
  rename: ^2.0.1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  intl: ^0.17.0
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  injectable_generator:
  json_serializable:
  freezed: ^2.3.2




flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Korto
      fonts:
        - asset: assets/fonts/Korto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Korto-BoldOblique.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Korto-Book.ttf
          weight: 400
        - asset: assets/fonts/Korto-BookOblique.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Korto-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Korto-HeavyOblique.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Korto-Light.ttf
          weight: 300
        - asset: assets/fonts/Korto-LightOblique.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Korto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Korto-MediumOblique.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Korto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Korto-ThinOblique.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Korto-Ultra.ttf
          weight: 900
        - asset: assets/fonts/Korto-UltraOblique.ttf
          weight: 900
          style: italic